# .github/workflows/ci-cd.yml

name: CI/CD Pipeline for C Program

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GCC
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build the application
      run: make

    - name: Ensure test script is executable
      run: chmod +x ./test.sh

    - name: Run and test the application
      run: ./test.sh

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server
      run: |
        echo "Deploying the application..."
        # Add your deployment commands here, e.g., scp, rsync, etc.
